# Generated by Django 3.1.3 on 2021-05-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True, verbose_name='first_name')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email')),
                ('last_name', models.CharField(max_length=20, null=True, verbose_name='last_name')),
                ('password', models.CharField(max_length=20, null=True, verbose_name='password')),
                ('rpassword', models.CharField(max_length=20, null=True, verbose_name='confirm')),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('video', models.FileField(upload_to='video/')),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('user_class', models.CharField(max_length=100, null=True, verbose_name='user_class')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='Subject')),
                ('chapter', models.IntegerField(null=True, verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
    ]
