# Generated by Django 3.1.3 on 2021-05-14 12:08

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.MyAccountManager()),
            ],
        ),
    ]
