# Generated by Django 3.1.3 on 2021-05-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210520_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rpassword',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
