# Generated by Django 3.1.3 on 2021-06-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210614_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
